# -*- coding: utf-8 -*-
"""list.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CbA669xNzwaqdh_1D9XGsdbC7Z52LZev
"""

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)