# -*- coding: utf-8 -*-
"""soting.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BB6jkOIUSlY-lgsaaVht01RU-ZMO7pxK

Selection Sort
"""

# selection sort
import sys
A = [64, 25, 12, 22, 11] # array

for i in range(len(A)): #loop for pointing

	min_idx = i
	for j in range(i+1, len(A)): #loop after pointed array
		if A[min_idx] > A[j]: #
			min_idx = j

	A[i], A[min_idx] = A[min_idx], A[i]

print ("Sorted array")
for i in range(len(A)):
	print("%d" %A[i],end=" , ")

def bubbleSort(arr):
	n = len(arr)
	swapped = False
	for i in range(n-1):
		for j in range(0, n-i-1):
			if arr[j] > arr[j + 1]:
				swapped = True
				arr[j], arr[j + 1] = arr[j + 1], arr[j]

		if not swapped:
			return

arr = [64, 34, 25, 12, 22, 11, 90]

bubbleSort(arr)

print("Sorted array is:")
for i in range(len(arr)):
	print("% d" % arr[i], end=" ")