# -*- coding: utf-8 -*-
"""string.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cjJEXDBYqVq8wsNzHZ2osg_84EMpHNLs
"""

#check if an expression present thr string
text = "hey i am abhishek"
if("expansive" not in text):
  print("no it is not present in the text variable")

text = "hey i am abhishek"
print("expansive"  in text)

#slicing of string
string =  "manav_rachna_internation_intitute_research_studies"
print(string[:9])
print("\nslicing after from the previous slic\n")
print(string[9:])

#negative indexing
stre = "hey_i_am_abhishek"
print(stre[-5:-2])

print("enter any string")
a = input()
if(a.upper()):
  print(a.upper())
elif(a.lower()):
  print(a.lower)
elif(a.strip()):
  print(a.strip)
elif(a.replace("h","j")):
  print(a.lower)
else:
  print("error")

# formate
age = 36
aas = "hello"
te ="my name {1} , {0} he he "
print(te.format(aas,age))

ttt = " fnaodnvsxf\"vikings\""

